In [1]:
import numpy as np


In [11]:
a = np.array([1,2,3])
print(a)
#get shape
# p = a.shape
print("get the shape: ",a.shape)
# #get dimension
# g = a.ndim
print("get the dimension : ",a.ndim)

[1 2 3]
get the shape:  (3,)
get the dimension :  1


In [14]:
b = np.array([[1.0,2.0,3],[3.0,9.0,4],[3.0,9.0,6]])
print(b)
#get shape
print("get the shape : ",b.shape)

#get dimension
m=b.ndim
print("get the dimension : ",m)

#Get type
print("datatype is : ",b.dtype)

#get Size
b.itemsize
print("get itemsize : ",b.itemsize)

#get total size --> like b.itemsize *b.size
b.nbytes
print("to get the total size : ",b.nbytes)

[[1. 2. 3.]
 [3. 9. 4.]
 [3. 9. 6.]]
get the shape :  (3, 3)
get the dimension :  2
datatype is :  float64
get itemsize :  8
to get the total size :  72


**Accessing and changing rows and columns**

In [16]:
k = np.array([[1,2,3,4,5,6],[2,4,65,7,8,4]])
print(k)
print("printing the shape : ",k.shape)

#get specific item from the array 
print("to get the specific location element from the arrray : ",k[1,3])

[[ 1  2  3  4  5  6]
 [ 2  4 65  7  8  4]]
printing the shape :  (2, 6)
to get the specific location element from the arrray :  7


In [ ]:
#get a row
k[1,:]

array([ 2,  4, 65,  7,  8,  4])

In [52]:
#get a column
k[:,1]

array([2, 4])

In [54]:
#to get somthing like [row, start:end:step]
k[0,1:6:2]

array([2, 4, 6])

In [60]:
k[0,1] = -22
print(k)
k[:,3] = [0,0]
k

[[  1 -22   3   0   5   6]
 [  2   4  65   0   8   4]]


array([[  1, -22,   3,   0,   5,   6],
       [  2,   4,  65,   0,   8,   4]])

In [66]:
#3d 
m = np.array([[[1,2,3],[2,2,2]],[[3,3,3],[5,5,7]]])
m[1,1,2]

np.int64(7)

In [67]:
print(m)

[[[1 2 3]
  [2 2 2]]

 [[3 3 3]
  [5 5 7]]]


Initialize different types of Arrays


In [71]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [72]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#get the full desired dimension with values
np.full((3,3),100)


array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [74]:
# any other number full_like
np.full_like(m,-88)

array([[[-88, -88, -88],
        [-88, -88, -88]],

       [[-88, -88, -88],
        [-88, -88, -88]]])

In [84]:
#for some random numbers
j = np.random.randint(low=0, high=100, size=(4,4))
print(j)

[[74 89 66 17]
 [ 7 99 84  9]
 [92 98 34 22]
 [37 50 86 24]]


In [85]:
#create identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [97]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
print(z)
z[1,1] = 9
print(z)
output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#Be careful when copying 

In [100]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)
print(b)
#instead do this
b = a.copy()
b[2] = -1
print(a)
print(b)

[100   2   3]
[100   2   3]
[100   2   3]
[100   2  -1]
