In [2]:
import numpy as np


In [11]:
a = np.array([1,2,3])
print(a)
#get shape
# p = a.shape
print("get the shape: ",a.shape)
# #get dimension
# g = a.ndim
print("get the dimension : ",a.ndim)

[1 2 3]
get the shape:  (3,)
get the dimension :  1


In [14]:
b = np.array([[1.0,2.0,3],[3.0,9.0,4],[3.0,9.0,6]])
print(b)
#get shape
print("get the shape : ",b.shape)

#get dimension
m=b.ndim
print("get the dimension : ",m)

#Get type
print("datatype is : ",b.dtype)

#get Size
b.itemsize
print("get itemsize : ",b.itemsize)

#get total size --> like b.itemsize *b.size
b.nbytes
print("to get the total size : ",b.nbytes)

[[1. 2. 3.]
 [3. 9. 4.]
 [3. 9. 6.]]
get the shape :  (3, 3)
get the dimension :  2
datatype is :  float64
get itemsize :  8
to get the total size :  72


**Accessing and changing rows and columns**

In [3]:
k = np.array([[1,2,3,4,5,6],[2,4,65,7,8,4]])
print(k)
print("printing the shape : ",k.shape)

#get specific item from the array 
print("to get the specific location element from the arrray : ",k[1,3])

[[ 1  2  3  4  5  6]
 [ 2  4 65  7  8  4]]
printing the shape :  (2, 6)
to get the specific location element from the arrray :  7


In [4]:
#get a row
k[1,:]

array([ 2,  4, 65,  7,  8,  4])

In [5]:
#get a column
k[:,1]

array([2, 4])

In [6]:
#to get somthing like [row, start:end:step]
k[0,1:6:2]

array([2, 4, 6])

In [7]:
k[0,1] = -22
print(k)
k[:,3] = [0,0]
k

[[  1 -22   3   4   5   6]
 [  2   4  65   7   8   4]]


array([[  1, -22,   3,   0,   5,   6],
       [  2,   4,  65,   0,   8,   4]])

In [8]:
#3d 
m = np.array([[[1,2,3],[2,2,2]],[[3,3,3],[5,5,7]]])
m[1,1,2]

np.int64(7)

In [20]:
print(m)
print(m.shape)

[[[1 2 3]
  [2 2 2]]

 [[3 3 3]
  [5 5 7]]]
(2, 2, 3)


**Initialize different types of Arrays**


In [10]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
#get the full desired dimension with values
np.full((3,3),100)


array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [14]:
# any other number full_like
np.full_like(m,-88)

array([[[-88, -88, -88],
        [-88, -88, -88]],

       [[-88, -88, -88],
        [-88, -88, -88]]])

In [17]:
#for some random numbers
j = np.random.randint(low=0, high=100, size=(4,4))
print(j)

[[ 5 72 11 30]
 [88 88  1  5]
 [34 65 90 94]
 [21 70 83 69]]


In [18]:
#create identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
#repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
# creating 5*5 matrix
output = np.ones((5,5))
print(output)

#creating 3*3 matrix
z = np.zeros((3,3))
print(z)

#replacing the centre element with 9
z[1,1] = 9
print(z)

#now replacing the old one inner matrix with the new desired matrix
output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**Be careful when copying** 

In [23]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)
print(b)

#instead do this
b = a.copy()
b[2] = -1
print(a)
print(b)

[100   2   3]
[100   2   3]
[100   2   3]
[100   2  -1]


**Mathematics using Numpy**

In [32]:
a = np.array([1,1,1])
print(a)

#adding a number throughtout 
print("adding a number throughtout : ",a+2)

#multiplying the no. throughout
print("multiplying the no. throughout ",a*2)

#all arthematic possible

#can add to arrays
b = np.array([3,3,3])
print("can add to array : ",a + b)

#tan of a array
print("tan of a array: ",np.tan(a),np.tan(b))

[1 1 1]
adding a number throughtout :  [3 3 3]
multiplying the no. throughout  [2 2 2]
can add to array :  [4 4 4]
tan of a array:  [1.55740772 1.55740772 1.55740772] [-0.14254654 -0.14254654 -0.14254654]


**Linear Algebra**

In [46]:
#lets defin two matrices
a = np.full((3,2),4)
print(a)

b = np.full((2,4),7)
print(b)

print("\n multiplying two matrices :\n ")
np.matmul(a,b)

[[4 4]
 [4 4]
 [4 4]]
[[7 7 7 7]
 [7 7 7 7]]

 multiplying two matrices :
 


array([[56, 56, 56, 56],
       [56, 56, 56, 56],
       [56, 56, 56, 56]])

In [48]:
#find the determinant
c = np.identity(3)
print(c)

print("det of c")
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
det of c


np.float64(1.0)

**Statistics**

In [57]:
a = np.array([[1,2,3],[24,53,6]])
print(a)

print("min : ",np.min(a))
print("max : ",np.max(a))
print("average : ",np.average(a))
print("median : ", np.median(a))
print("sum : ", np.sum(a,axis=1))

[[ 1  2  3]
 [24 53  6]]
min :  1
max :  53
average :  14.833333333333334
median :  4.5
sum :  [ 6 83]


**Reorganizing arrray**

In [62]:
before = np.array([[1,2,3,1],[2,1,4,6]])
print(before)

after = before.reshape(2,2,2)

[[1 2 3 1]
 [2 1 4 6]]


In [ ]:
#vertical stalking vectors
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.vstack([a,b]))

[[1 2 3]
 [4 5 6]]


In [71]:
#horizontal stacking 
h1 = np.zeros((2,3))
print(h1)
h2 = np.ones((2,4))
print(h2)
print(np.hstack((h1, h2)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1.]]


**Test Time**

Creating an array 

In [5]:
import numpy as np
a = np.array([1,2,3])
b = np.array([[1,1,1],[2,2,2]])
print("1 dimentional array: ", a)
print("shows the dimension : ",a.ndim)

print(b,b.shape)

1 dimentional array:  [1 2 3]
shows the dimension :  1
[[1 1 1]
 [2 2 2]] (2, 3)


Slicing & Indexing

In [ ]:
#printing from an index till end
print(a[1:,])

#printing selected 
print(b[1,2]) # second row third column element


[2 3]
2


Vectorized Ops

In [17]:
print(a *2)


[2 4 6]


In [22]:
#Matrix Multiplication

m = np.ones([2,2])
n = np.array([[2,3],[3,4]])

k = np.dot(m,n)
print(k)

#or

print(np.matmul(m,n))

[[5. 7.]
 [5. 7.]]
[[5. 7.]
 [5. 7.]]


Stats Ops

In [23]:
print(np.mean(n))

3.0


Reshape/Transpose

In [26]:
# Reshape m to a 1D array (flatten)
print(np.reshape(m, -1))

[1. 1. 1. 1.]
